[Engineering] setting up database
henrytomsf/FunDSProject pull request #4
Opened 2020-10-05 02:35 UTC by henrytomsf

1. database set up in aws
2. auth to db
3. read/write to db

2020-10-06 04:39 UTC, vincentpham1991 requested changes

2020-10-06 04:39 UTC, vincentpham1991 commented on database/dbQuery.py
> +    query = '''
shouldn't you put these in unit tests?

2020-10-06 04:39 UTC, vincentpham1991 commented on database/dbQuery.py
> +    dataTuple = [(6, 'vinny', 'vinny@gmail.com'),
no

2020-10-06 09:05 UTC, henrytomsf commented on database/dbQuery.py
> +    query = '''
added TODO for you 🎉

2020-10-06 09:05 UTC, henrytomsf commented on database/dbQuery.py
> +    dataTuple = [(6, 'vinny', 'vinny@gmail.com'),
yes

2020-10-09 02:02 UTC, vincentpham1991 approved these changes
Fine!

2020-10-09 09:18 UTC, merged